name: Docker Image CI

on:
  push:
    paths:
      -backend/**
      -.github/workflows/backend_CICD.yml
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    working-directory: './backend'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
    
    - name: Build the Docker image
      run: docker build --platform linux/amd64 -t ${{secrets.DOCKERHUB_USERNAME}}/sprout-backend:latest .
    - name: push
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/sprout-backend:latest
      

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} # EC2 인스턴스 퍼블릭 DNS
        username: ec2-user
        key: ${{ secrets.PRIVATE_KEY }} # pem 키
        # 도커 작업
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sprout-backend:latest
          docker stop main
          docker remove main
          docker run -d --log-driver=syslog -p 8000:8000  --network app --env-file .env  --name main ${{ secrets.DOCKERHUB_USERNAME }}/sprout-backend:latest
          docker image prune -a -f
